site_name: Altbrow

nav:
  - Home: index.md
  - Provider: provider.md
  - Configuration API: api.md
  - Configuration TOML: config.md
  - Exit Codes: exitcodes.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
